#!/bin/bash
# Written by Ben Vreeland
# Writes copyright info to image files using exiftool

while getopts ":v" opt; do
	case $opt in
	v)
		echo "Verbose output enabled." >&2
		v=1
		;;
	esac
done
shift $((OPTIND - 1))

# Assume the author is me if no name is passed in
if [[ "$1" ]]; then
	author="$1"
else
	author="Ben Vreeland"
fi

echo -e "Updating files for $author...\n"

shopt -s globstar nullglob nocaseglob
total=0
totalskip=0
for f in **/*.{jpg,jpeg,tif,tiff,dng,cr2,nef}; do
	if [[ "$f" ]]; then
		if [[ $(exiftool -s3 -Creator "$f") = "$author" ]]; then
			if [[ "$v" ]]; then
				echo "skipping $f"
			fi
			totalskip=$(( $totalskip + 1 ))
			continue
		fi

		fshort=${f##*/}
		year=$(exiftool -s3 -d '%Y' -DateTimeOriginal "$f")
		if [[ "$year" ]]; then
			yearpad=$year" "
		elif [[ ${fshort} =~ ^[0-9]{8}_ ]]; then
			year=${fshort:0:4}
			yearpad=$year" "
		fi

		exiftool \
			-q \
			-overwrite_original \
			-Copyright="$yearpad$author" \
			-CopyrightNotice="Copyright $yearpad$author" \
			-XPAuthor="$author" \
			-Artist="$author" \
			-Creator="$author" \
			-xmp:CopyrightYear=$year \
			-xmp:ArtworkCopyrightNotice="Copyright $yearpad$author" \
			-Comment="Copyright $yearpad$author" \
			"$f"

		if [[ "$v" ]]; then
			echo "updated $f"
		fi
		total=$(( $total + 1 ))
		year=""
		yearpad=""
	fi
done

if [[ "$v" ]]; then
	echo ""
fi
echo -e "$totalskip files already up to date"
echo -e "$total files updated for $author"
