#!/bin/bash

# Write copyright info to image files.

AUTHOR="Ben Vreeland"

shopt -s globstar nullglob nocaseglob
for f in **/*.{jpg,jpeg,tif,tiff,dng,cr2,nef}; do
	if [ -n "$f" ]; then
		fshort=${f##*/}
		YEAR=$(exiftool -s3 -d '%Y' -DateTimeOriginal $f)
		if [ -n "$YEAR" ]; then
			YEARPAD=$YEAR" "
		elif [[ ${fshort} =~ ^[0-9]{8}_ ]]; then
			YEAR=${fshort:0:4}
			YEARPAD=$YEAR" "
		fi
		exiftool \
			-q \
			-overwrite_original \
			-Copyright="$YEARPAD$AUTHOR" \
			-CopyrightNotice="Copyright $YEARPAD$AUTHOR" \
			-XPAuthor="$AUTHOR" \
			-Artist="$AUTHOR" \
			-Creator="$AUTHOR" \
			-xmp:CopyrightYear=$YEAR \
			-xmp:ArtworkCopyrightNotice="Copyright $YEARPAD$AUTHOR" \
			$f
	fi
done
